# wt.R
#radian
library(ggplot2)
library(tidyverse)
library(data.table)
source("../../R/readadmb.R")
source("../../R/helper.R")
mex1<-read_dat("mex1.dat")
mex2<-read_dat("mex2.dat")
pnw<-read_dat("pnw.dat")
glimpse(pnw)
system("wt -ind pnw.dat")
names(pnw)
df_dat <- data.frame(year=df$pnw_yrs,wt=df$pnw,source="PNW")
df_dat <- rbind(df_dat,data.frame(year=df$Mex1_yrs,wt=df$Mex1,source="Mex 1"))
df_dat <- rbind(df_dat,data.frame(year=df$Mex2_yrs,wt=df$Mex2,source="Mex 2"))
df_pre <- read_rep("wt.rep")
df_pre <- data.frame(year=df_pre$yr,df_pre$wt_pre,source="Predicted") 
names(df_dat) <- c("year",0:10,"source")
names(df_pre) <- c("year",0:10,"source")
df_all <-rbind(df_dat,df_pre) |>   mutate(source=fct_relevel(source, "PNW","Mex 1","Mex 2","Predicted"))
#fn_plot_anoms <- function(dfin, maxage=10,firstyr=1982,minage=3,txtsize=3){
fn_plot_anoms(df_all,maxage=6,minage=0)
system("wt -ind mex1.dat")
df_pre <- read_rep("wt.rep")
df_pre <- data.frame(year=df_pre$yr,df_pre$wt_pre,source="Predicted") 
df_all <-rbind(df_dat,df_pre) |>   mutate(source=fct_relevel(source, "Mex 1", "PNW","Mex 2","Predicted"))
fn_plot_anoms(df_all,maxage=6,minage=0)

